name: Integration test

on:
  - push

jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: stable

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test
          