name: Integration test

on:
  - push

jobs:
  android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [31]

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: stable

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          profile: Nexus 6
          script: flutter test integration_test
          